export const archivedCopy = {
  title: 'Archived',
  breadcrumbProjects: 'Projects',
  breadcrumbArchived: 'Archived',
  searchPlaceholder: 'Search archived tasks',
  searchAriaLabel: 'Search archived tasks',
  contextBand: (projectTitle: string) =>
    `Archived tasks in ${projectTitle}. Restoring returns them to their original column.`,
  sortDate: 'Sort: Archive date',
  sortName: 'Sort: Name',
  clearFilters: 'Clear filters',
  loadOlder: (remaining: number) => `View older (${remaining})`,
  restore: 'Restore',
  export: 'Export',
  delete: 'Delete permanently',
  undo: 'Undo',
  viewArchived: 'View archived',
  adminOnly: 'Only owners and admins can restore or delete archived tasks.',
  readOnly: 'Read only. Restore this task to edit it.',
  kicker: 'Archived task',
  columnWhenArchived: 'Column when archived',
  subtasks: 'Subtasks',
  archived: 'Archived',
  comments: (count: number) => (count === 1 ? '1 comment' : `${count} comments`),
  selectAll: 'Select all',
  selectNone: 'None',
  selectAllShort: 'All',
  clearSelection: 'Clear selection',
  exitSelection: 'Exit selection',
  ranges: {
    all: { label: 'Any date', short: 'All' },
    '7': { label: 'Last 7 days', short: '7 d' },
    '30': { label: 'Last 30 days', short: '30 d' },
    old: { label: 'Older than 30 days', short: '+30 d' },
  },
  headers: {
    name: 'Task',
    column: 'Column',
    subtasks: 'Subtasks',
    assignees: 'Assignees',
    archived: 'Archived',
  },
  deleteTitleOne: 'Delete this task?',
  deleteTitleMany: (n: number) => `Delete ${n} tasks?`,
  deleteBody: (name: string) =>
    `"${name}" is permanently deleted, with its comments and history. This cannot be undone.`,
  deleteBodyMany: (n: number) =>
    `${n} tasks are permanently deleted, with their comments and history. This cannot be undone.`,
  cancel: 'Cancel',
  deleteConfirm: 'Delete',
  deleteConfirmPhone: 'Delete permanently',
  exportTitle: 'Export as',
  exportCsv: 'CSV',
  exportJson: 'JSON',
  restoredOne: (name: string) => `"${name}" restored`,
  restoredMany: (n: number) => `${n} tasks restored`,
  deletedOne: (name: string) => `"${name}" permanently deleted`,
  deletedMany: (n: number) => `${n} tasks permanently deleted`,
  exportToast: (n: number) => `Preparing download of ${n} tasks`,
  swipeRestore: 'Restore',
  swipeDelete: 'Delete',
} as const;
